### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by xujinxing1996** [71yuu/YMall#14]
请问这个项目后端本地是怎么启动呢？

**Comment by 71yuu** [comment]
将api和admin这两个项目部署到tomcat就可以了

**Comment by xujinxing1996** [comment]
> 将api和admin这两个项目部署到tomcat就可以了

谢谢回复，我现在把admin启动了，但是api的启动会报错，是因为我Redis和Elasticsearch没启动吗？

**Comment by xujinxing1996** [comment]
> 将api和admin这两个项目部署到tomcat就可以了

![WX20200313-174026](https://user-images.githubusercontent.com/20754758/76609106-c8922a00-6551-11ea-8cc9-c0dc293e1537.png)
![2](https://user-images.githubusercontent.com/20754758/76609157-de075400-6551-11ea-91b9-2213269b9a63.png)
![3](https://user-images.githubusercontent.com/20754758/76609206-f37c7e00-6551-11ea-8a50-6932ccf0d77f.png)

**Comment by xujinxing1996** [comment]
> 将api和admin这两个项目部署到tomcat就可以了

能加你qq请教吗？

**Comment by 71yuu** [comment]
> > 将api和admin这两个项目部署到tomcat就可以了
> 
> 能加你qq请教吗？

加我QQ 1225459207

**Comment by Elif-lfp** [comment]
项目在9999端口上一片空白，其他页面都是空白，不知道api哪里出了问题

**Comment by woshiliyang** [comment]
我build aliyun sdk之后还是找不到dependency

**Comment by woshiliyang** [comment]
[https://github.com/woshiliyang/public/blob/master/8U%4005T_HO5)AX%5B%7DZR%40J6)ZI.png](url)

**Comment by woshiliyang** [comment]
![image](https://github.com/woshiliyang/public/blob/master/8U%4005T_HO5)AX%5B%7DZR%40J6)ZI.png)

**Comment by woshiliyang** [comment]
![](https://github.com/woshiliyang/public/blob/master/8U%4005T_HO5)AX%5B%7DZR%40J6)ZI.png)

**Comment by woshiliyang** [comment]
> 请问这个项目后端本地是怎么启动呢？

> 请问这个项目后端本地是怎么启动呢？

> 请问这个项目后端本地是怎么启动呢？

请问为什么我mvn install lib目录下的 aliyunsdk-20161215  pom还是 无法找到这个dependency  报Cannot resolve com.alipay:alipay-trade-sdk:20161215这个错误，老哥能帮帮忙看看吗  qq444042314
